laravel/app/routes.php
<?php

Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('home', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('seguros/para-voce/{slug?}', array('as' => 'seguros.pessoais', 'uses' => 'SegurosController@pessoais'));
Route::get('seguros/para-empresas/{slug?}', array('as' => 'seguros.empresas', 'uses' => 'SegurosController@empresas'));
Route::get('parceiros', array('as' => 'parceiros', 'uses' => 'ParceirosController@index'));
Route::get('em-caso-de-sinistro', array('as' => 'sinistro', 'uses' => 'SinistroController@index'));
Route::get('quem-somos', array('as' => 'quemsomos', 'uses' => 'QuemSomosController@index'));
Route::get('links-uteis', array('as' => 'linksuteis', 'uses' => 'LinksUteisController@index'));
Route::get('fale-conosco', array('as' => 'faleconosco', 'uses' => 'FaleConoscoController@index'));
Route::post('fale-conosco', array('as' => 'faleconosco.post', 'uses' => 'FaleConoscoController@enviar'));
Route::get('cotacao', array('as' => 'cotacao.auto', 'uses' => 'CotacaoController@auto'));
Route::get('cotacao/auto', array('as' => 'cotacao.auto', 'uses' => 'CotacaoController@auto'));
Route::post('cotacao/auto', array('as' => 'cotacao.auto.gravar', 'uses' => 'CotacaoController@gravarAuto'));
Route::get('cotacao/outros', array('as' => 'cotacao.outros', 'uses' => 'CotacaoController@outros'));
Route::post('cotacao/outros', array('as' => 'cotacao.outros.gravar', 'uses' => 'CotacaoController@gravarOutros'));

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

Route::post('cadastroNewsletter', 'HomeController@cadastro');

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{

    Route::get('download', function(){

    	$filename = 'cadastros_'.date('d-m-Y-H-i-s');

		Excel::create($filename, function($excel) {

		    $excel->sheet('Usuários Cadastrados', function($sheet) {

		        $sheet->fromModel(\Cadastro::select('nome', 'email')->orderBy('nome')->get());

		    });

		})->download('csv');

    });

    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('chamadalateral', 'Painel\ChamadaLateralController');
	Route::resource('banners', 'Painel\BannersController');
	Route::resource('chamadas', 'Painel\ChamadasController');
	Route::resource('cadastros', 'Painel\CadastrosController');
	Route::resource('seguropessoal', 'Painel\SeguroPessoalController');
	Route::resource('seguroempresarial', 'Painel\SeguroEmpresarialController');
	Route::resource('cotacoesoutras', 'Painel\CotacoesOutrasController');
	Route::resource('parceiros', 'Painel\ParceirosController');
	Route::resource('sinistro', 'Painel\SinistroController');
	Route::resource('contatoseguradoras', 'Painel\ContatoSeguradorasController');
	Route::resource('quemsomos', 'Painel\QuemSomosController');
	Route::resource('linksuteis', 'Painel\LinksUteisController');
	Route::resource('faleconosco', 'Painel\FaleConoscoController');
	Route::resource('cotacoesauto', 'Painel\CotacoesAutoController');
//NOVASROTASDOPAINEL//
});

laravel/app/models/Parceiro.php
<?php

class Parceiro extends Eloquent
{

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'parceiros';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array();

	// array of attributes we CAN set on the backend
    protected $fillable = array('', 'created_at', 'updated_at');

    // and those we CAN'T set on the backend
    protected $guarded = array('id');

    public function scopeOrdenado($query)
    {
    	return $query->orderBy('ordem', 'ASC')->get();
    }
}

laravel/app/controllers/ParceirosController.php
<?php

use \Parceiro;

class ParceirosController extends BaseController {

	protected $layout = 'frontend.templates.index';

	public function index()
	{
		$this->layout->content = View::make('frontend.parceiros.index')->with('listaParceiros', Parceiro::ordenado());
	}

}

laravel/app/controllers/painel/ParceirosController.php
<?php

namespace Painel;

use \View, \Input, \Str, \Session, \Redirect, \Hash, \Thumb, \Tools, \File, \Parceiro;

class ParceirosController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	protected $limiteInsercao = false;

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('backend.parceiros.index')->with('registros', Parceiro::ordenado());
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('backend.parceiros.form');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new Parceiro;

		$object->titulo = Input::get('titulo');

		$imagem = Thumb::make('imagem', 182, 142, 'parceiros/');
		if($imagem) $object->imagem = $imagem;
	
		try {

			$object->save();

			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Parceiro criado com sucesso.');
			return Redirect::route('painel.parceiros.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Parceiro!'));	

		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('backend.parceiros.edit')->with('registro', Parceiro::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = Parceiro::find($id);

		$object->titulo = Input::get('titulo');

		$imagem = Thumb::make('imagem', 182, 142, 'parceiros/');
		if($imagem) $object->imagem = $imagem;
	
		try {

			$object->save();
			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Parceiro alterado com sucesso.');
			return Redirect::route('painel.parceiros.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Parceiro!'));

		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = Parceiro::find($id);
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Parceiro removido com sucesso.');

		return Redirect::route('painel.parceiros.index');
	}

}

laravel/app/views/backend/parceiros/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Editar Parceiro
        </h2>  

		{{ Form::open( array('route' => array('painel.parceiros.update', $registro->id), 'files' => true, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	


				<div class="form-group">
					<label for="inputTítulo">Título</label>
					<input type="text" class="form-control" id="inputTítulo" name="titulo" value="{{$registro->titulo}}" required>
				</div>
				
				<div class="form-group">
					@if($registro->imagem)
						Imagem Atual<br>
						<img src="assets/images/parceiros/{{$registro->imagem}}"><br>
					@endif
					<label for="inputImagem">Trocar Imagem</label>
					<input type="file" class="form-control" id="inputImagem" name="imagem">
				</div>
				

				<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

				<a href="{{URL::route('painel.parceiros.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/parceiros/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Parceiro
        </h2>  

		<form action="{{URL::route('painel.parceiros.store')}}" method="post" enctype="multipart/form-data">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif


				<div class="form-group">
					<label for="inputTítulo">Título</label>
					<input type="text" class="form-control" id="inputTítulo" name="titulo" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['titulo'] }}" @endif required>
				</div>
				
				<div class="form-group">
					<label for="inputImagem">Imagem</label>
					<input type="file" class="form-control" id="inputImagem" name="imagem" required>
				</div>
				

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.parceiros.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/parceiros/index.blade.php
@section('conteudo')

<div class="container">

    @if(Session::has('sucesso'))
        <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <h2>
        Parceiros <a href='{{ URL::route('painel.parceiros.create') }}' class='btn btn-success btn-sm pull-right'><span class='glyphicon glyphicon-plus-sign'></span> Adicionar Parceiro</a>
    </h2>

    <table class='table table-striped table-bordered table-hover table-sortable' data-tabela='parceiros'>

        <thead>
            <tr>
                <th>Ordenar</th>
				<th>Título</th>
				<th>Imagem</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)

            <tr class="tr-row" id="row_{{ $registro->id }}">
                <td class='move-actions'><a href='#' class='btn btn-info btn-move btn-sm'>mover</a></td>
				<td>{{ $registro->titulo }}</td>
				<td><img src='assets/images/parceiros/{{ $registro->imagem }}' style='max-width:150px'></td>
                <td class="crud-actions">
                    <a href='{{ URL::route('painel.parceiros.edit', $registro->id ) }}' class='btn btn-primary btn-sm'>editar</a>
						{{ Form::open(array('route' => array('painel.parceiros.destroy', $registro->id), 'method' => 'delete')) }}
							<button type='submit' class='btn btn-danger btn-sm btn-delete'>excluir</button>
						{{ Form::close() }}                    
                </td>
            </tr>

        @endforeach
        </tbody>

    </table>

    
</div>

@stop